//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""NavigateDefaultUI"",
            ""id"": ""d51ea264-0db1-452f-bbc7-b359fcb85727"",
            ""actions"": [
                {
                    ""name"": ""ButtonPress"",
                    ""type"": ""PassThrough"",
                    ""id"": ""15af84bc-8bf4-424e-b3b9-20152843ca63"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressPosition"",
                    ""type"": ""Value"",
                    ""id"": ""bb5af798-d0ad-4149-9a9d-2d0dbba779ea"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryPress"",
                    ""type"": ""Button"",
                    ""id"": ""a3a2b6e4-67d2-431b-bbea-3e1dc7048303"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f82d9c14-e716-4776-a84c-ce6e1d771f5c"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4f7b364-3f86-4723-b77a-29adb92e2285"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da1fcb4f-92da-4ffa-875e-33792e761525"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ed4a279-10fb-4f07-adf9-a2b842426bcd"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65d4e7f6-ecb3-4c3d-b941-598bfcb0388e"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""NavigateDefaultUI1"",
            ""id"": ""b527d86d-2937-4d7e-a4d3-9705935e8ace"",
            ""actions"": [
                {
                    ""name"": ""ButtonPress"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2bd38d62-51f5-4658-b5a8-76a0c1c492de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressPosition"",
                    ""type"": ""Value"",
                    ""id"": ""bd0d7130-ccd4-4522-8213-9f98281dcc98"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryPress"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9f24c678-abfc-4050-ab86-d03a909dca30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""34bcd68b-5f5f-4ca7-a80b-d9efbd7ec761"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84c0919f-3288-47c0-be94-3f78396e316d"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3097c826-483c-45c7-85de-bc29670fd25c"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c56f4858-a6e9-4d0a-a922-c37653bd2f15"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bb4d173-7f1b-453b-b17e-ee8d5e646cfc"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a150b6ff-fada-4b58-ba04-ab34e58d29c7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // NavigateDefaultUI
        m_NavigateDefaultUI = asset.FindActionMap("NavigateDefaultUI", throwIfNotFound: true);
        m_NavigateDefaultUI_ButtonPress = m_NavigateDefaultUI.FindAction("ButtonPress", throwIfNotFound: true);
        m_NavigateDefaultUI_PressPosition = m_NavigateDefaultUI.FindAction("PressPosition", throwIfNotFound: true);
        m_NavigateDefaultUI_PrimaryPress = m_NavigateDefaultUI.FindAction("PrimaryPress", throwIfNotFound: true);
        // NavigateDefaultUI1
        m_NavigateDefaultUI1 = asset.FindActionMap("NavigateDefaultUI1", throwIfNotFound: true);
        m_NavigateDefaultUI1_ButtonPress = m_NavigateDefaultUI1.FindAction("ButtonPress", throwIfNotFound: true);
        m_NavigateDefaultUI1_PressPosition = m_NavigateDefaultUI1.FindAction("PressPosition", throwIfNotFound: true);
        m_NavigateDefaultUI1_PrimaryPress = m_NavigateDefaultUI1.FindAction("PrimaryPress", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // NavigateDefaultUI
    private readonly InputActionMap m_NavigateDefaultUI;
    private List<INavigateDefaultUIActions> m_NavigateDefaultUIActionsCallbackInterfaces = new List<INavigateDefaultUIActions>();
    private readonly InputAction m_NavigateDefaultUI_ButtonPress;
    private readonly InputAction m_NavigateDefaultUI_PressPosition;
    private readonly InputAction m_NavigateDefaultUI_PrimaryPress;
    public struct NavigateDefaultUIActions
    {
        private @PlayerInputActions m_Wrapper;
        public NavigateDefaultUIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ButtonPress => m_Wrapper.m_NavigateDefaultUI_ButtonPress;
        public InputAction @PressPosition => m_Wrapper.m_NavigateDefaultUI_PressPosition;
        public InputAction @PrimaryPress => m_Wrapper.m_NavigateDefaultUI_PrimaryPress;
        public InputActionMap Get() { return m_Wrapper.m_NavigateDefaultUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NavigateDefaultUIActions set) { return set.Get(); }
        public void AddCallbacks(INavigateDefaultUIActions instance)
        {
            if (instance == null || m_Wrapper.m_NavigateDefaultUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NavigateDefaultUIActionsCallbackInterfaces.Add(instance);
            @ButtonPress.started += instance.OnButtonPress;
            @ButtonPress.performed += instance.OnButtonPress;
            @ButtonPress.canceled += instance.OnButtonPress;
            @PressPosition.started += instance.OnPressPosition;
            @PressPosition.performed += instance.OnPressPosition;
            @PressPosition.canceled += instance.OnPressPosition;
            @PrimaryPress.started += instance.OnPrimaryPress;
            @PrimaryPress.performed += instance.OnPrimaryPress;
            @PrimaryPress.canceled += instance.OnPrimaryPress;
        }

        private void UnregisterCallbacks(INavigateDefaultUIActions instance)
        {
            @ButtonPress.started -= instance.OnButtonPress;
            @ButtonPress.performed -= instance.OnButtonPress;
            @ButtonPress.canceled -= instance.OnButtonPress;
            @PressPosition.started -= instance.OnPressPosition;
            @PressPosition.performed -= instance.OnPressPosition;
            @PressPosition.canceled -= instance.OnPressPosition;
            @PrimaryPress.started -= instance.OnPrimaryPress;
            @PrimaryPress.performed -= instance.OnPrimaryPress;
            @PrimaryPress.canceled -= instance.OnPrimaryPress;
        }

        public void RemoveCallbacks(INavigateDefaultUIActions instance)
        {
            if (m_Wrapper.m_NavigateDefaultUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(INavigateDefaultUIActions instance)
        {
            foreach (var item in m_Wrapper.m_NavigateDefaultUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NavigateDefaultUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public NavigateDefaultUIActions @NavigateDefaultUI => new NavigateDefaultUIActions(this);

    // NavigateDefaultUI1
    private readonly InputActionMap m_NavigateDefaultUI1;
    private List<INavigateDefaultUI1Actions> m_NavigateDefaultUI1ActionsCallbackInterfaces = new List<INavigateDefaultUI1Actions>();
    private readonly InputAction m_NavigateDefaultUI1_ButtonPress;
    private readonly InputAction m_NavigateDefaultUI1_PressPosition;
    private readonly InputAction m_NavigateDefaultUI1_PrimaryPress;
    public struct NavigateDefaultUI1Actions
    {
        private @PlayerInputActions m_Wrapper;
        public NavigateDefaultUI1Actions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ButtonPress => m_Wrapper.m_NavigateDefaultUI1_ButtonPress;
        public InputAction @PressPosition => m_Wrapper.m_NavigateDefaultUI1_PressPosition;
        public InputAction @PrimaryPress => m_Wrapper.m_NavigateDefaultUI1_PrimaryPress;
        public InputActionMap Get() { return m_Wrapper.m_NavigateDefaultUI1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NavigateDefaultUI1Actions set) { return set.Get(); }
        public void AddCallbacks(INavigateDefaultUI1Actions instance)
        {
            if (instance == null || m_Wrapper.m_NavigateDefaultUI1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NavigateDefaultUI1ActionsCallbackInterfaces.Add(instance);
            @ButtonPress.started += instance.OnButtonPress;
            @ButtonPress.performed += instance.OnButtonPress;
            @ButtonPress.canceled += instance.OnButtonPress;
            @PressPosition.started += instance.OnPressPosition;
            @PressPosition.performed += instance.OnPressPosition;
            @PressPosition.canceled += instance.OnPressPosition;
            @PrimaryPress.started += instance.OnPrimaryPress;
            @PrimaryPress.performed += instance.OnPrimaryPress;
            @PrimaryPress.canceled += instance.OnPrimaryPress;
        }

        private void UnregisterCallbacks(INavigateDefaultUI1Actions instance)
        {
            @ButtonPress.started -= instance.OnButtonPress;
            @ButtonPress.performed -= instance.OnButtonPress;
            @ButtonPress.canceled -= instance.OnButtonPress;
            @PressPosition.started -= instance.OnPressPosition;
            @PressPosition.performed -= instance.OnPressPosition;
            @PressPosition.canceled -= instance.OnPressPosition;
            @PrimaryPress.started -= instance.OnPrimaryPress;
            @PrimaryPress.performed -= instance.OnPrimaryPress;
            @PrimaryPress.canceled -= instance.OnPrimaryPress;
        }

        public void RemoveCallbacks(INavigateDefaultUI1Actions instance)
        {
            if (m_Wrapper.m_NavigateDefaultUI1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(INavigateDefaultUI1Actions instance)
        {
            foreach (var item in m_Wrapper.m_NavigateDefaultUI1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NavigateDefaultUI1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public NavigateDefaultUI1Actions @NavigateDefaultUI1 => new NavigateDefaultUI1Actions(this);
    public interface INavigateDefaultUIActions
    {
        void OnButtonPress(InputAction.CallbackContext context);
        void OnPressPosition(InputAction.CallbackContext context);
        void OnPrimaryPress(InputAction.CallbackContext context);
    }
    public interface INavigateDefaultUI1Actions
    {
        void OnButtonPress(InputAction.CallbackContext context);
        void OnPressPosition(InputAction.CallbackContext context);
        void OnPrimaryPress(InputAction.CallbackContext context);
    }
}
