//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Player Input Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Input Actions"",
    ""maps"": [
        {
            ""name"": ""Navigate Default UI"",
            ""id"": ""d51ea264-0db1-452f-bbc7-b359fcb85727"",
            ""actions"": [
                {
                    ""name"": ""ButtonPress"",
                    ""type"": ""PassThrough"",
                    ""id"": ""15af84bc-8bf4-424e-b3b9-20152843ca63"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2ed4a279-10fb-4f07-adf9-a2b842426bcd"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da1fcb4f-92da-4ffa-875e-33792e761525"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Navigate Default UI
        m_NavigateDefaultUI = asset.FindActionMap("Navigate Default UI", throwIfNotFound: true);
        m_NavigateDefaultUI_ButtonPress = m_NavigateDefaultUI.FindAction("ButtonPress", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Navigate Default UI
    private readonly InputActionMap m_NavigateDefaultUI;
    private List<INavigateDefaultUIActions> m_NavigateDefaultUIActionsCallbackInterfaces = new List<INavigateDefaultUIActions>();
    private readonly InputAction m_NavigateDefaultUI_ButtonPress;
    public struct NavigateDefaultUIActions
    {
        private @PlayerInputActions m_Wrapper;
        public NavigateDefaultUIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ButtonPress => m_Wrapper.m_NavigateDefaultUI_ButtonPress;
        public InputActionMap Get() { return m_Wrapper.m_NavigateDefaultUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NavigateDefaultUIActions set) { return set.Get(); }
        public void AddCallbacks(INavigateDefaultUIActions instance)
        {
            if (instance == null || m_Wrapper.m_NavigateDefaultUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NavigateDefaultUIActionsCallbackInterfaces.Add(instance);
            @ButtonPress.started += instance.OnButtonPress;
            @ButtonPress.performed += instance.OnButtonPress;
            @ButtonPress.canceled += instance.OnButtonPress;
        }

        private void UnregisterCallbacks(INavigateDefaultUIActions instance)
        {
            @ButtonPress.started -= instance.OnButtonPress;
            @ButtonPress.performed -= instance.OnButtonPress;
            @ButtonPress.canceled -= instance.OnButtonPress;
        }

        public void RemoveCallbacks(INavigateDefaultUIActions instance)
        {
            if (m_Wrapper.m_NavigateDefaultUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(INavigateDefaultUIActions instance)
        {
            foreach (var item in m_Wrapper.m_NavigateDefaultUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NavigateDefaultUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public NavigateDefaultUIActions @NavigateDefaultUI => new NavigateDefaultUIActions(this);
    public interface INavigateDefaultUIActions
    {
        void OnButtonPress(InputAction.CallbackContext context);
    }
}
